### ISSUE TITLE
The tooltip in the Visual Studio shows an error

### ISSUE THREAD

**Issue by eagle-k** [tatsuya-midorikawa/Funtom.Linq#4]
The tooltip for `Linq.select'` will show an error.
(`Linq.select` will display the tooltip as expected.)

![image](https://user-images.githubusercontent.com/87229746/147872831-f150f0ec-8a07-4b5d-9ef9-eb53d047d893.png)

The following is for copy and paste.

```fs
testCase "test"
  <| fun _ ->
      let xs = [ 1 .. 5 ]
      let ys = xs |> Linq.select' (*)
      Expect.equal ys [ 1; 4; 9; 16; 25 ] "select with index"
```

I used Visual Studio 2022 and installed this library (Funtom.Linq v0.0.3) with Nuget.
The test itself passes, so there is no problem with the runtime.

**Comment by tatsuya-midorikawa** [comment]
Hi, @eagle-k 

`Linq.select'` can be obtained with value and index as parameters.
Therefore, your code will be expanded as follows:
```fsharp
let xs = [ 1 .. 5 ]
let ys = xs |> Linq.select' (fun value index -> value * index)
```
In other words, you need to specify `[ 0; 2; 6; 12; 20; ]` as the expected value.  

I recommend that you modify the test code as follows:
```fsharp
testCase "test"
  <| fun _ ->
    let xs = [ 1 .. 5 ]
    let ys = xs |> Linq.select' (*)
    let expects = [| 0; 2; 6; 12; 20; |]
    for i = 0 to expects.Length do
      Expect.equal ys[i] expects[i] "select with index"
```

Thanks,
midoliy

**Comment by eagle-k** [comment]
Sorry for the confusion, the test case is wrong.

The main issue is that the tooltip for `select'` is not displayed correctly in the IDE.
I am getting internal errors in both Visual Studio 2022 and Visual Studio Code.

There is no problem at runtime.

**Comment by tatsuya-midorikawa** [comment]
I was able to confirm the error on my end as well.
![image](https://user-images.githubusercontent.com/78302178/147893814-71c5aeae-fb7d-4f3e-ba94-99fa04e535af.png)

It seems that there is a problem with F# Language Sever.
It is difficult to fix it on the library side, so I will report it to the Visual Studio team.
