### ISSUE TITLE
[Proposal] Property-based test via FsCheck

### ISSUE THREAD

**Issue by delneg** [tatsuya-midorikawa/Funtom.Linq#9]
Hello,
I propose we implement some property-based test via https://github.com/fscheck/FsCheck for the purpose of ensuring the correctness of the code (because if it doesn't behave right, it doesn't matter how fast it is after all) - in order to make this library a worthy alternative of fsharp.core / system.linq methods (whcih are both extensively tested).
I hope I'll be able to send in a PR sometime soon

**Comment by tatsuya-midorikawa** [comment]
Hi, delneg!
I'm very grateful for your proposal, there are things that I may not realize on my own.
If you send me a PR, I will check the content and merge it!

**Comment by delneg** [comment]
Started work in https://github.com/tatsuya-midorikawa/Funtom.Linq/pull/10

**Comment by tatsuya-midorikawa** [comment]
Grateful thanks!
